version: '3'

services:
  db:
    image: postgres
  web:
    build: ./backend/
    command: python3 ./backend/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/kreate
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      ./backend/.env