version: '3'

services:
  db:
    image: postgres
  web:
    build: ./backend/
    command: python3 ./backend/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/kreate
    # ports:
    #   - "8000:8000"
    depends_on:
      - db
    environment:
      VIRTUAL_HOST: dev-kreateph.com
      VIRTUAL_PORT: 8000
    env_file:
      ./backend/.env